/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OCTToken } from "./OCTToken";
export type { ServiceRegistry } from "./ServiceRegistry";
export type { Staking } from "./Staking";
