/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ServiceRegistry {
  export type ServiceStruct = {
    name: string;
    description: string;
    metadataURI: string;
    provider: AddressLike;
    tier: BigNumberish;
    price: BigNumberish;
    usageCount: BigNumberish;
    totalRevenue: BigNumberish;
    isActive: boolean;
    registeredAt: BigNumberish;
  };

  export type ServiceStructOutput = [
    name: string,
    description: string,
    metadataURI: string,
    provider: string,
    tier: bigint,
    price: bigint,
    usageCount: bigint,
    totalRevenue: bigint,
    isActive: boolean,
    registeredAt: bigint
  ] & {
    name: string;
    description: string;
    metadataURI: string;
    provider: string;
    tier: bigint;
    price: bigint;
    usageCount: bigint;
    totalRevenue: bigint;
    isActive: boolean;
    registeredAt: bigint;
  };
}

export interface ServiceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DESCRIPTION_LENGTH"
      | "MIN_PRICE"
      | "batchUseServices"
      | "claimEarnings"
      | "getDefaultPriceByTier"
      | "getProviderServices"
      | "getService"
      | "getServiceCount"
      | "getUserServiceUsage"
      | "octToken"
      | "owner"
      | "pause"
      | "paused"
      | "pendingEarnings"
      | "platformFee"
      | "providerEarnings"
      | "providerServices"
      | "registerService"
      | "renounceOwnership"
      | "serviceIds"
      | "services"
      | "setPlatformFee"
      | "setServiceStatus"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateService"
      | "useService"
      | "userUsage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentDistributed"
      | "PlatformFeeUpdated"
      | "ServiceRegistered"
      | "ServiceStatusChanged"
      | "ServiceUpdated"
      | "ServiceUsed"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DESCRIPTION_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchUseServices",
    values: [BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultPriceByTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderServices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getService",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getServiceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserServiceUsage",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "octToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "providerServices",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerService",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serviceIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "services", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setServiceStatus",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateService",
    values: [BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "useService",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userUsage",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DESCRIPTION_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchUseServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultPriceByTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getService", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getServiceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserServiceUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "octToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "serviceIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "services", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setServiceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userUsage", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentDistributedEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    provider: AddressLike,
    providerAmount: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: string,
    provider: string,
    providerAmount: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    serviceId: string;
    provider: string;
    providerAmount: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceRegisteredEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    name: string,
    provider: AddressLike,
    tier: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: string,
    name: string,
    provider: string,
    tier: bigint,
    price: bigint
  ];
  export interface OutputObject {
    serviceId: string;
    name: string;
    provider: string;
    tier: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceStatusChangedEvent {
  export type InputTuple = [serviceId: BytesLike, isActive: boolean];
  export type OutputTuple = [serviceId: string, isActive: boolean];
  export interface OutputObject {
    serviceId: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceUpdatedEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    description: string,
    metadataURI: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: string,
    description: string,
    metadataURI: string,
    price: bigint
  ];
  export interface OutputObject {
    serviceId: string;
    description: string;
    metadataURI: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceUsedEvent {
  export type InputTuple = [
    serviceId: BytesLike,
    user: AddressLike,
    amount: BigNumberish,
    newTotalSpent: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: string,
    user: string,
    amount: bigint,
    newTotalSpent: bigint
  ];
  export interface OutputObject {
    serviceId: string;
    user: string;
    amount: bigint;
    newTotalSpent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ServiceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ServiceRegistry;
  waitForDeployment(): Promise<this>;

  interface: ServiceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DESCRIPTION_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE: TypedContractMethod<[], [bigint], "view">;

  batchUseServices: TypedContractMethod<
    [_serviceIds: BytesLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimEarnings: TypedContractMethod<[], [bigint], "nonpayable">;

  getDefaultPriceByTier: TypedContractMethod<
    [tier: BigNumberish],
    [bigint],
    "view"
  >;

  getProviderServices: TypedContractMethod<
    [provider: AddressLike],
    [string[]],
    "view"
  >;

  getService: TypedContractMethod<
    [serviceId: BytesLike],
    [ServiceRegistry.ServiceStructOutput],
    "view"
  >;

  getServiceCount: TypedContractMethod<[], [bigint], "view">;

  getUserServiceUsage: TypedContractMethod<
    [user: AddressLike, serviceId: BytesLike],
    [bigint],
    "view"
  >;

  octToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingEarnings: TypedContractMethod<
    [provider: AddressLike],
    [bigint],
    "view"
  >;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  providerEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  providerServices: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  registerService: TypedContractMethod<
    [
      name: string,
      description: string,
      metadataURI: string,
      tier: BigNumberish,
      price: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  serviceIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  services: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        name: string;
        description: string;
        metadataURI: string;
        provider: string;
        tier: bigint;
        price: bigint;
        usageCount: bigint;
        totalRevenue: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  setPlatformFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setServiceStatus: TypedContractMethod<
    [serviceId: BytesLike, isActive: boolean],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateService: TypedContractMethod<
    [
      serviceId: BytesLike,
      description: string,
      metadataURI: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  useService: TypedContractMethod<
    [serviceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  userUsage: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { totalSpent: bigint; requestCount: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DESCRIPTION_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchUseServices"
  ): TypedContractMethod<
    [_serviceIds: BytesLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimEarnings"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getDefaultPriceByTier"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProviderServices"
  ): TypedContractMethod<[provider: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getService"
  ): TypedContractMethod<
    [serviceId: BytesLike],
    [ServiceRegistry.ServiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getServiceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserServiceUsage"
  ): TypedContractMethod<
    [user: AddressLike, serviceId: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "octToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingEarnings"
  ): TypedContractMethod<[provider: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "providerEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "providerServices"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerService"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      metadataURI: string,
      tier: BigNumberish,
      price: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "serviceIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "services"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        name: string;
        description: string;
        metadataURI: string;
        provider: string;
        tier: bigint;
        price: bigint;
        usageCount: bigint;
        totalRevenue: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setServiceStatus"
  ): TypedContractMethod<
    [serviceId: BytesLike, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateService"
  ): TypedContractMethod<
    [
      serviceId: BytesLike,
      description: string,
      metadataURI: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useService"
  ): TypedContractMethod<
    [serviceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userUsage"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { totalSpent: bigint; requestCount: bigint }],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentDistributed"
  ): TypedContractEvent<
    PaymentDistributedEvent.InputTuple,
    PaymentDistributedEvent.OutputTuple,
    PaymentDistributedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceRegistered"
  ): TypedContractEvent<
    ServiceRegisteredEvent.InputTuple,
    ServiceRegisteredEvent.OutputTuple,
    ServiceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ServiceStatusChanged"
  ): TypedContractEvent<
    ServiceStatusChangedEvent.InputTuple,
    ServiceStatusChangedEvent.OutputTuple,
    ServiceStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceUpdated"
  ): TypedContractEvent<
    ServiceUpdatedEvent.InputTuple,
    ServiceUpdatedEvent.OutputTuple,
    ServiceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceUsed"
  ): TypedContractEvent<
    ServiceUsedEvent.InputTuple,
    ServiceUsedEvent.OutputTuple,
    ServiceUsedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentDistributed(bytes32,address,uint256,uint256)": TypedContractEvent<
      PaymentDistributedEvent.InputTuple,
      PaymentDistributedEvent.OutputTuple,
      PaymentDistributedEvent.OutputObject
    >;
    PaymentDistributed: TypedContractEvent<
      PaymentDistributedEvent.InputTuple,
      PaymentDistributedEvent.OutputTuple,
      PaymentDistributedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "ServiceRegistered(bytes32,string,address,uint8,uint256)": TypedContractEvent<
      ServiceRegisteredEvent.InputTuple,
      ServiceRegisteredEvent.OutputTuple,
      ServiceRegisteredEvent.OutputObject
    >;
    ServiceRegistered: TypedContractEvent<
      ServiceRegisteredEvent.InputTuple,
      ServiceRegisteredEvent.OutputTuple,
      ServiceRegisteredEvent.OutputObject
    >;

    "ServiceStatusChanged(bytes32,bool)": TypedContractEvent<
      ServiceStatusChangedEvent.InputTuple,
      ServiceStatusChangedEvent.OutputTuple,
      ServiceStatusChangedEvent.OutputObject
    >;
    ServiceStatusChanged: TypedContractEvent<
      ServiceStatusChangedEvent.InputTuple,
      ServiceStatusChangedEvent.OutputTuple,
      ServiceStatusChangedEvent.OutputObject
    >;

    "ServiceUpdated(bytes32,string,string,uint256)": TypedContractEvent<
      ServiceUpdatedEvent.InputTuple,
      ServiceUpdatedEvent.OutputTuple,
      ServiceUpdatedEvent.OutputObject
    >;
    ServiceUpdated: TypedContractEvent<
      ServiceUpdatedEvent.InputTuple,
      ServiceUpdatedEvent.OutputTuple,
      ServiceUpdatedEvent.OutputObject
    >;

    "ServiceUsed(bytes32,address,uint256,uint256)": TypedContractEvent<
      ServiceUsedEvent.InputTuple,
      ServiceUsedEvent.OutputTuple,
      ServiceUsedEvent.OutputObject
    >;
    ServiceUsed: TypedContractEvent<
      ServiceUsedEvent.InputTuple,
      ServiceUsedEvent.OutputTuple,
      ServiceUsedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
