/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OCTToken__factory } from "./OCTToken__factory";
export { ServiceRegistry__factory } from "./ServiceRegistry__factory";
export { Staking__factory } from "./Staking__factory";
